export type BookAvailability = "Available" | "Unavailable";
export type BookGenre =
  | "none"
  | "Fiction"
  | "Non-Fiction"
  | "Fantasy"
  | "Science Fiction"
  | "Mystery"
  | "Thriller"
  | "Horror"
  | "Romance"
  | "Historical"
  | "Young Adult"
  | "Children"
  | "Biography"
  | "Autobiography"
  | "Self-Help"
  | "Business"
  | "Philosophy"
  | "Religion"
  | "Poetry"
  | "Graphic Novel"
  | "Manga"
  | "Educational"
  | "Reference"
  | "Art"
  | "Travel"
  | "Health"
  | "Cooking";
